### ISSUE TITLE
Add favicon to chat space

### ISSUE THREAD

**Issue by brittag** [Roguelike-Celebration/azure-mud#354]
To help me quickly find it among the many tabs I'm checking. :D

**Comment by lazerwalker** [comment]
Add an @-sign roguelike icon to the repo, and it can also serve as a placeholder to show other folks how to add their own.

**Comment by lazerwalker** [comment]
This is a 5-minute job that takes no code.

**Comment by lazerwalker** [comment]
This exists!!
