### ISSUE TITLE
User report: if a message is 3 lines, chat doesn't scroll quite enough

### ISSUE THREAD

**Issue by brittag** [Roguelike-Celebration/azure-mud#356]
"If a message is long enough that it takes 3 lines, chat will only scroll down one line so you can't see the rest of the message without scrolling down"

Person says they're on Firefox on Linux

**Comment by lazerwalker** [comment]
When we auto-scroll, we tell the chat box to scroll the bottom-most message to the bottom. 

It's possible there's an option to specify that the _bottom_ (rather than the top) of the message should be visible.

Also possible this is a browser-dependent thing.

**Comment by lazerwalker** [comment]
Unsure if this is a problem in 2022.
