### ISSUE TITLE
Move message rendering to a lazy-loaded infinite-scroll list

### ISSUE THREAD

**Issue by lazerwalker** [Roguelike-Celebration/azure-mud#373]
An initial reason for limiting the number of messages in #372 was rendering performance. Switching over to an infinite-scroll library that lazily-loads messages will fix this. There are drop-in React ones we can use.

**Comment by lazerwalker** [comment]
I'm looking at https://github.com/bvaughn/react-virtualized

If I switch over to this, I'll want to:
* Remove the max limit stored in Storage
* Find a way to spam a few thousand messages and make sure we're not actually slowing things down

**Comment by lazerwalker** [comment]
Labeling this as a "good first issue" as something that requires moderate JS ability, but isn't really dependent on knowledge of our specific setup rather than just knowledge of React.

**Comment by mysterycommand** [comment]
Hi there, I think I could take a look at this but when I follow the [Frontend Dev](https://github.com/Roguelike-Celebration/azure-mud#frontend-dev) instructions I wind up with a blank screen and errors about my invalid API key (my whole `FIREBASE_CONFIG` is undefined) … is there a FE-only setup, or some secret config I could get to use the existing server setup?
