### ISSUE TITLE
the (n chatters offscreen) line has vanished somehow

### ISSUE THREAD

**Issue by MoyTW** [Roguelike-Celebration/azure-mud#533]
oh noooo!

**Comment by MoyTW** [comment]
This appears to have been intentional; it's replaced by a popup line which I remember being inaccurate for some reason but cannot recall now

**Comment by lazerwalker** [comment]
There was an intentional change (just show "N people are offscreen" if N > 0), but that seems to be broken in unspecified ways that are difficult to test locally without others.
