### ISSUE TITLE
Sanitize usernames and chat messages

### ISSUE THREAD

**Issue by lazerwalker** [Roguelike-Celebration/azure-mud#611]
In 2021, we had a user whose username was just the Unicode character to begin RTL text. This messed up the entire page, and we also couldn't select their username to ban them.

My gut instinct is we want a blocklist (probably easy to source?) of Unicode characters to strip from both usernames and messages, and then maybe a check to make sure the sanitized version is still > 0 characters.

Edge case to think about: are we being shitty to people who actually speak RTL languages? Is there a reasonable way to allow a RTL Arabic/Hebrew/etc username? Or is it reasonable to say "this space is in English, therefore usernames must use Latin characters"

**Comment by MoyTW** [comment]
Also, please limit the chat handle length to ~50 characters - right now you can enter handles of arbitrary length.

**Comment by MoyTW** [comment]
Addressed by https://github.com/Roguelike-Celebration/azure-mud/pull/634
