### ISSUE TITLE
Add a bunch more custom emoji

### ISSUE THREAD

**Issue by lazerwalker** [Roguelike-Celebration/azure-mud#657]
Custom emoji list:
- [x] moderator badge
- [x] speaker badge

**Comment by rmkubik** [comment]
Add URLs to [this JSON map](https://github.com/Roguelike-Celebration/azure-mud/blob/main/src/emoji/customEmojiMap.json) should be all that is needed to add new emoji.

We should be able to reference images hosted on our server in the "images" directory.
