### ISSUE TITLE
People inconsistently can't see their own notes on the note wall.

### ISSUE THREAD

**Issue by lazerwalker** [Roguelike-Celebration/azure-mud#670]
Other people could see their notes

**Comment by rmkubik** [comment]
Is there more information or thoughts on how I could re-produce this issue?

I have:
- Gone to Central Hall
- Clicked "Add Feedback"
- Added a test note
- Refreshed and checked the feedback several times
- Saw my note initially and have seen it on every refresh so far

**Comment by lazerwalker** [comment]
Wishing we'd captured more info on this during the preview event. There were a small number of people (more than 1, fewer than 5) who experienced this, and other people were able to confirm they could see those people's posts. 

Absolutely no idea what we can do if we can't reproduce.
